version: 2.1
orbs:
  gh-pages: sugarshin/gh-pages@0.0.6
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install
          command: sudo yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: yarn build
      - gh-pages/deploy:
          build-dir: public
          requires:
            - public
          ssh-fingerprints: 3a:44:28:e1:b0:59:4a:d8:c6:49:95:3e:d5:77:44:d8
