version: 2.1

orbs:
  gh-pages: sugarshin/gh-pages@0.0.6

jobs:
  install_and_build:
    docker:
      - image: circleci/node:10.19.0
    working_directory: $CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install
          command: sudo yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: yarn build

workflows:
  build_and_deploy:
    jobs:
      - install_and_build
      - gh-pages/deploy:
          requires:
            - install_and_build
          attach-workspace: false
          build-dir: public
          ssh-fingerprints: 3a:44:28:e1:b0:59:4a:d8:c6:49:95:3e:d5:77:44:d8
