version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: install
          command: sudo yarn install
      - run:
          name: build
          command: yarn build
      - run:
          name: deploy
          command: yarn deploy
